# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.


{
    'name': 'NHCL Customizations',
    'version': '1.0',
    'sequence': 1,
    'category': 'Purchase',
    "author": "New Horizons Cybersoft Ltd",
    "website": "https://www.nhclindia.com/",
    'summary': 'Purchase,Contact,Stock,Product Customizations',
    'description': """
This module contains all the common features of Transport and Check.
    """,
    'depends': ['purchase', 'base', 'stock', 'base_setup', 'product', 'hr', 'purchase_product_matrix', 'sale',
                'sale_purchase_inter_company_rules', 'approvals', 'approvals_purchase', 'purchase_stock', 'sale_stock',
                'hr_expense', 'fleet', 'account', 'mrp', 'stock_picking_batch', 'l10n_in', 'stock_account',
                'stock_landed_costs','stock_dropshipping'],
    'external_dependencies': {
        'python': ['odf', 'openpyxl', 'xlrd', 'XlsxWriter', 'pandas'],
    },
    'data': [
        'security/ir.model.access.csv',
        'security/sales_incentive_security.xml',
        'security/purchase_order_approval_groups.xml',
        'security/approval_request_groups.xml',
        "data/sequence.xml",
        'data/store_target_sequence.xml',
        "data/email_templates.xml",
        "data/update_return_slip.xml",
        "data/cron_jobs.xml",
        'report/store_target_report_template_view.xml',
        'views/contact_master.xml',
        "views/logistic_screen_entry.xml",
        "views/transports_check_view.xml",
        'views/placement_master.xml',
        'views/logistic_status_view.xml',
        "views/delivery_check_view.xml",
        "views/open_parel.xml",
        "views/cmr_logistic_server_actions.xml",
        "views/purchase_approval_buttons.xml",
        "views/approval_request_view.xml",
        "views/sale_order_view.xml",
        "views/account_move.xml",
        "views/manufacturing_view.xml",
        'views/master_sequence_views.xml',
        'views/product_template_views.xml',
        'views/stock_views.xml',
        'views/cmr_pics_upload.xml',
        'views/loyalty_view.xml',
        'views/hr_employee_view.xml',
        'wizard/serial_no_confirm_popup.xml',
        'wizard/import_order_lines_view.xml',
        'wizard/import_move_lines_view.xml',
        'wizard/import_bom_lines_view.xml',
        'wizard/import_mrp_prod_lines_view.xml',
        'wizard/import_promotions_view.xml',
        'wizard/loyalty_generate_wizard_views.xml',
        'views/res_users_views.xml',
        'data/sales_attachment_sample.xml',
        'wizard/import_approval_lines_view.xml',
        'wizard/import_po_lines_view.xml',
        'data/purchase_attachment_sample.xml',
        'wizard/import_invoice_lines_view.xml',
        'wizard/message_wizard_view.xml',
        'data/invoice_attachment_sample.xml',
        'views/transport_menu.xml',
        'views/transport_details_view.xml',
        'views/fleet_vehicle_view.xml',
        'views/routes_details_view.xml',
        'views/location_view.xml',
        'views/transport_entry_view.xml',
        'views/setu_sales_incentive_structure_views.xml',
        'views/setu_sales_incentive_structure_line_views.xml',
        'views/product_margin_approval_views.xml',
        'views/reprint_labels_view.xml',
        'views/master_data_views.xml',
        'views/vendor_return.xml',
        'views/store_wise_division_view.xml',
        'views/store_wise_report_views.xml',
        'report/dev_transport_report_template.xml',
        'report/dev_transport_report_menu.xml',
        'report/delivery_slip.xml',
        'report/report_picking_batch.xml',
        'report/stock_picking_batch_report_views.xml',
        'report/barcode_sheet.xml',
        'report/combo_report.xml',
        'report/report_deliveryslip.xml',
        'report/account_move_invoice_report.xml',
        'report/product_product_templates.xml',
        'report/po_indent_report.xml',
        'report/gate_pass_report.xml',
        'report/grc_cmr_text_tiles.xml',
        'report/grt_report.xml',
        'report/purchase_order_text_tiles.xml',
        'report/purchase_venodr_bill.xml',
        'report/text_tiles_delivery.xml',
        'report/text_tiles_tax_invoice.xml',
        'report/transfer_note.xml',
        'report/new_ODT_report.xml',
        'report/barcode_sheet_delivery.xml',
        'wizard/landed_cost_popup.xml',
        'wizard/stock_serial_number.xml',
        'wizard/change_to_backdate_wiz.xml',
        'wizard/import_stock_receipt_wizard.xml',
        'wizard/multi_product_view.xml',
        'wizard/print_label.xml',
        'wizard/multi_product_direct.xml',
        'wizard/approval_rejection_wizard.xml',
        'views/stock_verification_unmatched_view.xml',
        'views/loyalty_reward_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'cmr_customizations/static/src/scss/list_sticky_header.scss',
            'cmr_customizations/static/src/css/cmr_dashboard.css',
            'cmr_customizations/static/src/xml/cmr_dashboard.xml',
            'cmr_customizations/static/src/js/cmr_dashboard.js',
            'cmr_customizations/static/src/xml/approval_total_telugu.xml',
            'cmr_customizations/static/src/js/validation.js',
            'cmr_customizations/static/src/js/hide_cancel_icon.js',
            'cmr_customizations/static/src/fields/one2manysearch/one2manysearch.js',
            'cmr_customizations/static/src/js/patch_list_width_render.js',
            # 'cmr_customizations/static/src/js/switch_company.js',
            # 'cmr_customizations/static/src/xml/switch_company.xml',
            'cmr_customizations/static/src/fields/one2manysearch/one2manysearch_template.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
