{
    "name": "Ho to Store Integration",
    "category": "Extra Tools",
    "version": "17.0",
    'sequence': 2,
    "author": "New Horizons Cybersoft Ltd",
    "website": "https://www.nhclindia.com/",
    "description": """Ho to Store CMR Integration""",
    "depends": ['base', 'base_setup', 'cmr_customizations', 'account_accountant','stock_inventory_count_tus'],
    "data": [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/ho_store_transactions.xml',
        'views/product_template_view.xml',
        'views/product_category.xml',
        'views/product_attribute.xml',
        'views/hr_employee.xml',
        'views/product_product.xml',
        'views/contact.xml',
        'views/account_tax_view.xml',
        'views/account_account_view.xml',
        'views/loyalty_program_view.xml',
        'views/new_store_job_scheduler.xml',
        'views/gift_card_scheduler_action_view.xml',
        'views/replication_log_view.xml',
        'views/sale_incentive_view.xml',
        'views/partner_category.xml',
        'views/nhcl_product_uom.xml',
        'views/ir_cron_views.xml',
        'views/cv_ir_cron_history.xml',
        'views/product_aging_views.xml',
        'views/setu_sales_person_incentive_detailed_report.xml',
        'views/setu_sales_person_incentive_summary_report.xml',
        'views/summery_report_employee_wise.xml',
        'views/designation_wise_incentive_report.xml',
        "views/hsn_wise_tax_report.xml",
        "views/nhcl_pos_order_hour_report.xml",
        'views/bulk_replication.xml',
        "views/nhcl_pos_delivery_order_hour_report.xml",
        "views/nhcl_site_wise_sale_report_view.xml",
        "views/setu_sales_person_incentive_aging_report.xml",
        "views/mop.xml",
        "views/tax_repo.xml",
        "views/lfb.xml",
        "report/mop.xml",
        "report/tax_report.xml",
        "report/lfb.xml",
        'data/sequence.xml',
        'wizard/bulk_models_views.xml',
        'views/daily_sale_report_view.xml',
        'views/nhcl_store_audit_plan_view.xml',
        # 'views/last_scanned_serial_number_report_view.xml',
        'views/pos_audit_report_view.xml',
        'views/ho_audit_report_view.xml',
        'views/store_pos_audit_summary_view.xml',
        'views/ho_store_master_config.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'nhcl_ho_store_cmr_integration/static/src/xml/cmr_bulk_replication.xml',
            'nhcl_ho_store_cmr_integration/static/src/xml/tracking.xml',
            'nhcl_ho_store_cmr_integration/static/src/js/cmr_bulk_replication.js',
            'nhcl_ho_store_cmr_integration/static/src/js/tracking.js',
            # old
            'nhcl_ho_store_cmr_integration/static/src/xml/cmr_bulk_replication.xml',
            'nhcl_ho_store_cmr_integration/static/src/js/cmr_bulk_replication.js',
            'nhcl_ho_store_cmr_integration/static/src/cron_history_widget/cron_history_widget.js',
            'nhcl_ho_store_cmr_integration/static/src/cron_history_widget/cron_history_widget.xml',
            'nhcl_ho_store_cmr_integration/static/src/cron_history_widget/cron_history_widget.scss',
            'nhcl_ho_store_cmr_integration/static/src/xml/empty_page.xml',
            'nhcl_ho_store_cmr_integration/static/src/js/empty_page.js',
        ],
    },
    "demo": [],
    "application": True,
    "installable": True,
    "auto-intall": False
}
